admins: []
forwards:
- source: -1001716147792
  dest:
  - -1001790786586
  - -1001618361888
  offset: 1
  end: 0
- source: -1001603456835
  dest:
  - -1001517364988
  - -1001652219056
  offset: 1
  end: 0
- source: -1001746380559
  dest:
  - -1001642337915
  offset: 1
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  replace:
    text:
      '@MovieJunction - ': 'Join @REQ_MVS - '
      '@MovieJunctionChannel': Join @REQ_MVS
      regex: true
