admins: []
forwards:
- source: -1001774626738
  dest:
  - -1001780210726
  - -1001703199914
  offset: 2553
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  replace:
    text:
      '@MovieJunction - ': 'Join @REQ_MVS - '
      '@MovieJunctionChannel': Join @REQ_MVS
      regex: true
