admins: []
forwards:
- source: -1001603456835
  dest:
  - -1001596715722
  - -1001739535037
  offset: 1
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  replace:
    text:
      '@MovieJunction - ': 'Join @REQ_MVS - '
      '@MovieJunctionChannel': Join @REQ_MVS
      regex: true
