admins: []
forwards:
- source: -1001203936319
  dest:
  - -1001259984500
  offset: 1213
  end: 0
- source: -1001367522199
  dest:
  - -1001520686674
  offset: 2100
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
